# Generated by Django 4.0.4 on 2022-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_rename_lesson_commentaire_nom_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fpe',
            field=models.FileField(blank=True, null=True, upload_to='Answers', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Video', verbose_name='Video'),
        ),
    ]
