# Generated by Django 4.0.4 on 2022-05-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_alter_lesson_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='image',
        ),
    ]
