# Generated by Django 4.0.4 on 2022-05-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_remove_matiere_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='img'),
        ),
    ]
