# Generated by Django 4.0.4 on 2022-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_rename_photo_profile_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(choices=[('student', 'student'), ('lecturer', 'lecturer'), ('parent', 'parent')], default='student', max_length=100),
        ),
    ]
